package com.example.weather.ui.theme

import androidx.compose.ui.graphics.Color


val light_primary = Color(0xFF4156BA)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFDEE1FF)
val light_onPrimaryContainer = Color(0xFF001159)
val light_secondary = Color(0xFF00696E)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFF6FF6FE)
val light_onSecondaryContainer = Color(0xFF002022)
val light_tertiary = Color(0xFF7342BF)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFECDCFF)
val light_onTertiaryContainer = Color(0xFF270057)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFF8FDFF)
val light_onBackground = Color(0xFF434447)
val light_surface = Color(0xFFF8FDFF)
val light_onSurface = Color(0xFF001F25)

val dark_primary = Color(0xFFB9C3FF)
val dark_onPrimary = Color(0xFF03228A)
val dark_primaryContainer = Color(0xFF263CA1)
val dark_onPrimaryContainer = Color(0xFFDEE1FF)
val dark_secondary = Color(0xFF4CD9E2)
val dark_onSecondary = Color(0xFF00373A)
val dark_secondaryContainer = Color(0xFF004F53)
val dark_onSecondaryContainer = Color(0xFF6FF6FE)
val dark_tertiary = Color(0xFFD5BAFF)
val dark_onTertiary = Color(0xFF42008A)
val dark_tertiaryContainer = Color(0xFF5A25A6)
val dark_onTertiaryContainer = Color(0xFFECDCFF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF001F25)
val dark_onBackground = Color(0xFFA6EEFF)
val dark_surface = Color(0xFF001F25)
val dark_onSurface = Color(0xFFA6EEFF)

// public
val Black = Color(0xFF000000)
val white = Color(0xFFffffff)

